# Your bot account token. Create a bot account if you don't a bot account, get one and its token here -> https://discordapp.com/developers/applications/me/
token: "Put your token here!"
# All commands will use this symbol(s) before the command name. eg. &say has a prefix of &
prefix: "!"
# Will appear after "Playing" under the bots name. Set to nil to not show a game
playing: "type !help"

# These users will have full access to the bot's admin commands, and by extension, the server it is hosted on.
# Give this power with care!!
owner: 264499432538505217
secondary_owners:
  - 302534881370439681

# Status of the bot
online_status: ONLINE

# Set this false to use some production APIs.
debug: true

# The root server this bot will be based off.
root_server: 000000000000000000

# Set this to true to allow patching of config files via DM.
patch_mail: false

# Set this to true to enable Morpher running.
morpher_enabled: false

# The channel that Morpher will mirror messages from.
morpher_root: 000000000000000000

# The channel that Morpher will mirror messages to.
morpher_mirror: 000000000000000000

# Set this to true to enable checking of Birthdays.
birthdays_enabled: false

# The channel that Birthdays will be sent in.
birthdays_channel: 000000000000000000

# Set this to true to enable Sentry, if you don't know what is this leave it on false.
sentry_enabled: false

# Sentry DSN.
sentry_dsn: ""

# Reminder for the Music Night @ RC24
music_night_reminder: false

# Datadog connection info
datadog:
  enabled: false
  prefix: ""
  host: "localhost"
  port: 8125

database:
    # MySQL host.
    host: "localhost:3306"
    # MySQL user
    user: ""
    # MySQL user password.
    password: ""
    # MySQL database. MUST BE CREATED BEFORE!
    database: ""

    # Properties
    useSSL: true
    verifyServerCertificate: false
    autoReconnect: true

raid_prevention: false
